#include "macros.h"
#include "tBrain.h"

void _initPortCPins(uint8_t pinNumber) {
	PORTC->PCR[pinNumber] &= ~PORT_PCR_MUX_MASK;
	PORTC->PCR[pinNumber] |= PORT_PCR_MUX(4);
}

void initMotorControl() {
	SIM->SCGC5 |= SIM_SCGC5_PORTC_MASK;
	SIM->SCGC6 |= SIM_SCGC6_TPM0_MASK;
	SIM->SOPT2 &= ~SIM_SOPT2_TPMSRC_MASK;
	SIM->SOPT2 |= SIM_SOPT2_TPMSRC(1);
	TPM0->SC &= ~(TPM_SC_CMOD_MASK | TPM_SC_PS_MASK);
	TPM0->SC |= TPM_SC_CMOD(1) | TPM_SC_PS(7) | TPM_SC_CPWMS_MASK;
	TPM0->MOD = 3750;
	TPM0_C0SC &= ~(TPM_CnSC_ELSA_MASK | TPM_CnSC_ELSB_MASK | TPM_CnSC_MSA_MASK | TPM_CnSC_MSB_MASK);
	TPM0_C0SC |= TPM_CnSC_ELSB(1) | TPM_CnSC_MSB(1);
	TPM0_C1SC &= ~(TPM_CnSC_ELSA_MASK | TPM_CnSC_ELSB_MASK | TPM_CnSC_MSA_MASK | TPM_CnSC_MSB_MASK);
	TPM0_C1SC |= TPM_CnSC_ELSB(1) | TPM_CnSC_MSB(1);
	TPM0_C2SC &= ~(TPM_CnSC_ELSA_MASK | TPM_CnSC_ELSB_MASK | TPM_CnSC_MSA_MASK | TPM_CnSC_MSB_MASK);
	TPM0_C2SC |= TPM_CnSC_ELSB(1) | TPM_CnSC_MSB(1);
	TPM0_C3SC &= ~(TPM_CnSC_ELSA_MASK | TPM_CnSC_ELSB_MASK | TPM_CnSC_MSA_MASK | TPM_CnSC_MSB_MASK);
	TPM0_C3SC |= TPM_CnSC_ELSB(1) | TPM_CnSC_MSB(1);
	for (uint8_t i = 1; i <= 4; ++i) _initPortCPins(i);
};
